### ISSUE TITLE
 "contact list" using Firebase

### ISSUE THREAD

**Issue by thatianaviana** [thatianaviana/TravelBud#3]

**Comment by thatianaviana** [comment]
along with HTML code that go with it

**Comment by vpaula90** [comment]
also make it so the packing list can be emailed or pulled into PDF form or both

**Comment by vpaula90** [comment]
background image for the contact section

**Comment by vpaula90** [comment]
contact form needs to have validations. Make sure that email format is correct and filled in and that there is something in the text area:
https://getbootstrap.com/docs/4.3/components/forms/

**Comment by vpaula90** [comment]
Contact list using firebase was uploaded on 4/30

**Comment by vpaula90** [comment]
contact us was set up and is injecting the data to firebase
