### ISSUE TITLE
Create Translator API call + HTML code to go with that

### ISSUE THREAD

**Issue by thatianaviana** [thatianaviana/TravelBud#4]

**Comment by GMancillas9** [comment]
Researching and looking into the Google Cloud Translation API - Saturday 4/27

**Comment by GMancillas9** [comment]
Tutor suggested to find alternate API since Google Cloud Platform Translation API uses Node.js 
which we haven't covered in class - Monday 4/29

**Comment by GMancillas9** [comment]
Researched and found Yandex API, will now work on first draft of HTML + JS code - Tuesday 4/30

**Comment by GMancillas9** [comment]
hey team just pushed first draft of the translation portion of our site
